### ISSUE TITLE
Send 1st CFP

### ISSUE THREAD

**Issue by anwaldt** [linuxaudio/conference2018#10]
Send out cfp. The lists are now in the pad

**Comment by dvzrv** [comment]
We need an updated text for the mail I think.
Also, a footer regarding the involved institutions would be nice.

**Comment by ri0t** [comment]
@dvzrv , @anwaldt  - Which pad is this or where are the lists mentioned? I want to send out the Call For Lightning Talks to the same(?) lists - there are only three submissions right now :-/

**Comment by dvzrv** [comment]
@ri0t look into the sent folder of the lac mail account for the lists addressed.

**Comment by x42** [comment]
A _Call For Lightning Talks_  less than a week before the conference? and send it to 30+ high profile email lists?  I'll recommend against that. We'll embarrass ourselves and discredit the conference, won't we?

**Comment by dvzrv** [comment]
you might be right, that this is actually too late to send out.

**Comment by ri0t** [comment]
No, not to all of them. CCC lightning talks are announced quite shortly before as well.

**Comment by ri0t** [comment]
Hack'n'tell is even shorter - they collect the talks at the beginning of each session.

**Comment by fundamental** [comment]
Registration includes email so, wouldn't it be appropriate at this state to only email people who are attending the conference about the lightning talks?

**Comment by ri0t** [comment]
That kinda makes a lot of sense :-> Do we have a way to contact all participants already?

**Comment by dvzrv** [comment]
we have a list of registrants in the mail account.
now please stop necrobumping this issue
