### ISSUE TITLE
Participant registration

### ISSUE THREAD

**Issue by ri0t** [linuxaudio/conference2018#11]
Needs a system to register participants, so we know beforehand how many nerds we'll host and can possibly close registration after reaching a limit.

This could probably be part of the conference information system (infoscreens and session planning tool) i am building - it already has user registration.

**Comment by ri0t** [comment]
Needs these issues resolved in https://github.com/hackerfleet/hfos:
* [x] https://github.com/Hackerfleet/hfos/issues/282
* [x] https://github.com/Hackerfleet/hfos/issues/268
* [x] https://github.com/Hackerfleet/hfos/issues/244 (at least a few bits of that one)

**Comment by ri0t** [comment]
Hm. We'll definitely need 
* [x] TOS/Privacy/Cookie-legalese.

**Comment by ri0t** [comment]
* [x] Include swag (t-shirt) pre-order form!

**Comment by falkTX** [comment]
we have lac t-shirts?

**Comment by ri0t** [comment]
not per se... unless we find a way to manage the process, involving quite some work:
* manage preorders
* order shirts accordingly
* design/complete a nice shirt design
* fire up the shirt-manufacture, which in turn consists of (per shirt):
  * cut foil
  * pick foil outlines
  * fix foil on shirt by ironing

Also, the costs for the plotted material and probably one knife per ~23 to ~42 shirts need to be recuperated.
