### ISSUE TITLE
get concert venue

### ISSUE THREAD

**Issue by anwaldt** [linuxaudio/conference2018#13]
Room for 100-150 people.
- [x] Beta House (@franconassis)
- [x] AdK (@anwaldt )
- [x] delphi (@anwaldt )
- [ ] Sound Studies (@dvzrv)
- [x] Ohm (@ri0t )
- [ ] CRCL (https://crclr.org/spaces, 500€)
- [ ] Kater Holzig
- [ ] ETI (@ri0t)
- [ ] hybrid-lab (@anwaldt )
- [x] [artistania](http://artistania.org/) (@anwaldt , @dvzrv)

**Comment by anwaldt** [comment]
We have the Spektrum (http://spektrumberlin.de/home.html) for one event -
it is not so big, but ok.

**Comment by ri0t** [comment]
I was told a surprisingly low price for the Ohm. They're apparently just a bit picky about whom they let in, but i think, the Linux Sound Night might actually qualify...

**Comment by anwaldt** [comment]
So - who can I contact to make it happen?

**Comment by dvzrv** [comment]
we have artistania for the saturday. We'll most likely have to deal with a much smaller space for friday though...

**Comment by dvzrv** [comment]
we'll use c-base on friday evening

**Comment by dvzrv** [comment]
As we have this settled (afaics), I'll close this.
