### ISSUE TITLE
Send 2nd CfP

### ISSUE THREAD

**Issue by dvzrv** [linuxaudio/conference2018#14]
We need to send out the 2nd CfP soonish

**Comment by anwaldt** [comment]
@anwaldt 

- [x]  ak-staff@lists.tu-berlin.de
- [x]  ak-students@lists.tu-berlin.de
- [x]  lac-team@lists.linuxaudio.org
- [ ] DEGEM news 

@x42 

- [ ]  frei0r@lists.dyne.org
- [ ]   fluxus@lists.pawfal.org
- [x]   ardour-users@lists.ardour.org
- [ ]   foms@lists.annodex.net
- [ ]   sursound@music.vt.edu
- [x]  jack-devel@lists.jackaudio.org
- [x]  alsa-devel@alsa-project.org
- [x]    devel@lists.lv2plug.in
- [x]   linux-audio-announce@lists.linuxaudio.org
- [ ]    l2ork-dev@disis.music.vt.edu
- [ ]  hackers@lists.dyne.org
- [x]  gstreamer-devel@lists.freedesktop.org

@dvzrv

- [x]  communication@sounds.berlin
- [x]   linux-audio-dev@lists.linuxaudio.org
- [x]  linux-audio-user@lists.linuxaudio.org
- [x]  sc-users@lists.bham.ac.uk
- [x]  sc-dev@lists.bham.ac.uk
- [x]  discuss@linuxaudio.berlin
- [x]  lilypond-user@gnu.org
- [x]  livecode@toplap.org
- [x] arch-proaudio@lists.archlinux.org
- [x]   music.research@listes.ircam.fr
- [x]  music@lists.fedoraproject.org
- [x]  auditory@lists.mcgill.ca [takes time]
- [x]  ffado-user@lists.sourceforge.net
- [x]  liblo-devel@lists.sourceforge.net
- [x]  community@nime.org [meh, google groups]
- [x]  SOUNDSCAPEUK@JISCMAIL.AC.UK [???]
- [ ]  gif@piksel.no
- [x] pd-ot@lists.puredata.info

**Comment by dvzrv** [comment]
@x42 ping

**Comment by dvzrv** [comment]
Closing this now, as it has become irrelefant
