### ISSUE TITLE
Announce LAC CFP on online conference calenders

### ISSUE THREAD

**Issue by anwaldt** [linuxaudio/conference2018#16]
Has that been done for past LACs?

**Comment by dvzrv** [comment]
Not that I know of

**Comment by ri0t** [comment]
Me neither. Sounds like #18 - we need to advise people that they have to register, to really participate locally, so we don't get overcrowded in any case. I'll integrate that into the press statement.

**Comment by ri0t** [comment]
Has been integrated into the most important ones i could find.
