### ISSUE TITLE
Press statement

### ISSUE THREAD

**Issue by ri0t** [linuxaudio/conference2018#18]
Destinations:
* [x] Heise
* [x] LinuxMusicians.com
* [x] LinuxMagazin
* [ ] LinuxTag e.V.
* [x] LinuxJournal
* [x] LWN (Linux Weekly News)
* [x] Slashdot
* [ ] ...

Statement:
https://github.com/linuxaudio/conference2018/wiki/Press
German:
https://github.com/linuxaudio/conference2018/wiki/Presse

**Comment by falkTX** [comment]
I am admin at linuxmusicians.com, I can make the topic sticky to get more visibility.

**Comment by ri0t** [comment]
@dvzrv @Excds @anwaldt - any input/criticism on this? Otherwise i'd really like to send this out today.

**Comment by dvzrv** [comment]
@ri0t I updated it a little, but am travelling right now, so I don't have much time to really have a deep look into it.
Looks okay so far though.

**Comment by dvzrv** [comment]
Needs CfP link!

**Comment by ri0t** [comment]
@falkTX : https://linuxmusicians.com/viewtopic.php?f=13&t=18261

**Comment by ri0t** [comment]
https://slashdot.org/submission/7983621/linux-audio-conference---0706-10062018-c-base-berlin
