### ISSUE TITLE
Compile crew

### ISSUE THREAD

**Issue by dvzrv** [linuxaudio/conference2018#19]
We need a list of people that will help during the event:

- [x] stage hands
- [x] session chairs
- [x] camera/ video mixing
- [x] bar

**Comment by Excds** [comment]
Setup dudle for helpers.

http://dudle.inf.tu-dresden.de/

One for workshops (best with more technical people) and one for people being track chair (paper session, poster session).

**Comment by ri0t** [comment]
https://dudle.inf.tu-dresden.de/LAC18_Team/

Needs an invitation mail, stating that people should put their addresses and job-type as well.
Does it need more fine granularity?

**Comment by ri0t** [comment]
https://dudle.inf.tu-dresden.de/LAC18_Team/
https://dudle.inf.tu-dresden.de/LAC18_Stage/
https://dudle.inf.tu-dresden.de/LAC18_Video/
https://dudle.inf.tu-dresden.de/LAC18_Session/

**Comment by ri0t** [comment]
I think the text is okay. I'd post it to:
- ak-staff@lists.tu-berlin.de
- ak-students@lists.tu-berlin.de
- lac-team@lists.linuxaudio.org
- communication@sounds.berlin
- intern@c-base.org

Any other lists/targets?

**Comment by ri0t** [comment]
Maybe have a post on the homepage as well?

**Comment by dvzrv** [comment]
Yes, this should also go to the website. I'll write a post for it

**Comment by dvzrv** [comment]
I've also revised the text for the mailing lists. Not sure, if we can send to all of the mailing lists though (e.g. the AK ones have already been tried by @anwaldt). We could extend to lau.

**Comment by dvzrv** [comment]
anyhow... this can be sent out now and it would be great if @Excds could take over from here

**Comment by dvzrv** [comment]
The mail was sent. Only the post needs to be pushed now.

**Comment by dvzrv** [comment]
Posts posted.

**Comment by dvzrv** [comment]
Sent another mail to c-base internal mailing list.
