### ISSUE TITLE
Sponsor slide for talk intros

### ISSUE THREAD

**Issue by Excds** [linuxaudio/conference2018#23]
As we discussed that we would when presenting talks have one slide for LAC + talk name and one for sponsors before the rest of the talk slides, we still need to prepare those...

**Comment by Excds** [comment]
Graphics from Ableton.
[Ableton wordmark.zip](https://github.com/linuxaudio/conference2018/files/1747950/Ableton.wordmark.zip)

**Comment by ri0t** [comment]
I'll do those with the CIS. So yeah, let's collect the necessary assets here.

**Comment by dvzrv** [comment]
Can now also all just be grabbed [from the website](https://github.com/linuxaudio/lac2018/tree/master/files/images) (@150px height)

**Comment by dvzrv** [comment]
A simple pdf would do, too.

**Comment by ri0t** [comment]
[2018-05-14_Draft_1_1920x1080.pdf](https://github.com/linuxaudio/conference2018/files/2001634/2018-05-14_Draft_1_1920x1080.pdf)
[2018-05-14_Draft_1_1920x1200.pdf](https://github.com/linuxaudio/conference2018/files/2001635/2018-05-14_Draft_1_1920x1200.pdf)

**Comment by ri0t** [comment]
MOD needs to be added

**Comment by dvzrv** [comment]
HEDD and Native Instruments need to be added.

**Comment by dvzrv** [comment]
@ri0t where are the sources of the above pdfs?

**Comment by ri0t** [comment]
I think, the repo makes a fine place for that. MOD is already in, i don't have anything from HEDD or NI.

https://github.com/linuxaudio/conference2018/tree/master/sponsor_slide

**Comment by ri0t** [comment]
Bitwig needs to be added.

**Comment by Excds** [comment]
@ri0t Well, just add them then...
