### ISSUE TITLE
Accept VOC equipment and store at c-base

### ISSUE THREAD

**Issue by dvzrv** [linuxaudio/conference2018#24]
According to @derpeter, a delivery with the VOC hardware will arrive at c-base on May 30th.
A cey has to be there to accept the delivery and help store it (e.g. at soundlab).

As I might not be in Berlin that day, due to to some other planning, we need a volunteer.
@Excds @ri0t ?

**Comment by MaZderMind** [comment]
@dvzrv @ri0t Hi! I'm organizing the Logistics-Planning for C3VOC.

I planned on having the Hardware being delivered to c.base at **2018-05-30**. We need a Time-Window of at least 4 hours, where someone on site is able to accept the delivery. Preferrably between **9:00 and 17:00**.

The actual delivery address was communicated to me as
```
  c-base e.V.
  Rungestrasse 20
  10179 Berlin tc
```

I'd also need a **name** and a **mobile phone number** which will be called by the delivery people 5-10 minutes before the delivery.

The cases are around 70kg each and have wheels. (see https://c3voc.de/wiki/hardware:cases for details). If they need to be lifted, you'll need at least 2 person on-site.

**Comment by dvzrv** [comment]
@MaZderMind I will try to be available that day, but I can only be around in the early morning (until 9:45) or late afternoon (after 18:00), due to work.
You can find my contact details on my website.
Note that for c-base members to be around, it's usually better to choose a time window in the afternoon (if possible).

I will check, if another cey will be available that day.

**Comment by MaZderMind** [comment]
@dvzrv Okay, so I'll try to arrange delivery **on 2018-05-30 between 18:00 and 22:00**. I'll keep you updated here.

**Comment by ri0t** [comment]
I can be there earlier than 1800, just not before 1200.

**Comment by MaZderMind** [comment]
I requested delivery between 18:00 and 22:00 at the haulage now. I guess they charge us a little extra but it shouldn't be that much. I'd say let's see what they quote us and if it's too much I'll come back to you.

**Comment by MaZderMind** [comment]
So the special transport after 18:00 costs around 220€ extra. If @ri0t can be there earlier I would rather like to request delivery after, let's say, 14:00 – would that be ok?

**Comment by ri0t** [comment]
Absolutely!

**Comment by MaZderMind** [comment]
So, Transportation is now fixed to

>  An Berlin - 30.5. *14:00 Uhr or later*
>  David R**** - +49 176 *** *** 63
>  c-base e.V.
>  Rungestrasse 20
>  10179 Berlin tc

I'll open another ticket for pickup after the conference

**Comment by dvzrv** [comment]
@MaZderMind thanks!

**Comment by MaZderMind** [comment]
One more Update: On 30.5. we expect two Trucks to arrive::
 - no.1 carries 2 Flightcases from Heidelberg
 - no.1 carries 1 Flightcase from Paris

Both should arrive after 14:00 and both got the Phone number above. At the end of the day you shpuld have *3 Big Flightcases* with smaller ones strapped on top of them.

**Comment by dvzrv** [comment]
@MaZderMind I just had to deal with the arrival of the first two flightcases by rushing over from work to c-base and opening the space. Please tell the logistics company, that this is unacceptable (timing wise).

**Comment by MaZderMind** [comment]
@dvzrv 
> Hallo Herr …,
>
>die Cases sind in Berlin angekommen, allersings nicht wie abgesprochen nach 14:00. Hier die Beschwerde des Empfängers:
>
>> @MaZderMind I just had to deal with the arrival of the first two flightcases by rushing over from work to c-base and opening the space. Please tell the logistics company, that this is unacceptable (timing wise).
>
>Ich kann dem Kollegen hier nur zustimmen. Unsere Anlieferungs-Locations sind nicht permanent besetzt und die Speditionen melden sich auch oft erst, wenn sie schon vor dem Haus stehen.
>
>Ich würde Sie bitten, diese Beschwerde an die entsprechende Stelle weiter zu reichen.
>
>Vielen Dank,
>Peter Körner

**Comment by dvzrv** [comment]
@MaZderMind vielen Dank!

**Comment by MaZderMind** [comment]
@dvzrv Das andere Case hat gestern Paris verlassen und sollte gg. 14/16 Uhr bei euch eintreffen. Vielen Dank für deine Mühe!

**Comment by MaZderMind** [comment]
@dvzrv 
>Halo Herr Körner,
>
>vielen Dank für die Info.
>
>Dies ist natürlich extrem ärgerlich und ich kann mich für die Unannehmlichkeiten nur entschuldigen.
>
>Ich gebe dies umgehend an die entsprechende Abteilung weiter.
>
>Zur Info: Den Auftrag habe ich mit Anlieferung um 14 Uhr eingegeben und einem Fahreravis (Fahrer sollte sich mindestens 1 Stunde vor Ankunft melden).

**Comment by ri0t** [comment]
Die zweite Lieferung ist auch da. Haben wir ne Packliste, damit ich prüfen kann, ob alles da ist?

**Comment by MaZderMind** [comment]
@ri0t In den Cases ist eine kleinteil-Liste zum später packen. Für den Moment kannst du einfach mal ein Foto von dem machen was da ist.

Es sollten bei euch sein:
 - 3 Saal-Cases (groß, blau, mit Rollen)
 - 3 Audio-Cases (kleiner, braun)
 - 3 oder 4 Auer-Boxen Regie- und Spare-Parts
 - 2 Kabeltrommeln SDI-Kabel

Edit: wir haben Fotos:
Lieferung 1: https://c3voc.de/gallery/2018/DjangoCon/IMG_1412.jpeg.html (minus ein Video-Case)
Lieferung 2: https://c3voc.de/gallery/2018/DjangoCon/IMG_6313.JPG.html

**Comment by dvzrv** [comment]
@ri0t can we close this?

**Comment by ri0t** [comment]
Consider it closed. I just didn't have a good camera on me, to take my own pics. Will check with the photos and list, later, today.
