### ISSUE TITLE
Export for static webpage

### ISSUE THREAD

**Issue by ri0t** [linuxaudio/conference2018#27]
We need to be able to hit the button to export reStructuredText for sessions.
Misc stuff to watch there:
* [ ] Video-URL
* [ ] HFOS URL
* [x] Title, Description, Author, Datetime

**Comment by dvzrv** [comment]
As we have openconf already, we can use that data.
Need a conversion from there to VOC anyways.

**Comment by dvzrv** [comment]
event data is now in ics calendars and should remain there.
