### ISSUE TITLE
Point live.linuxaudio.org to CIS VM

### ISSUE THREAD

**Issue by ri0t** [linuxaudio/conference2018#29]
`live         IN  A     46.4.114.243    ; live conference info system`

Should be added to linuxaudio.org's DNS zone

**Comment by danielhjames** [comment]
Hi, https://live.linuxaudio.org/ is online although the certificate is self-signed so there will be browser warnings.

**Comment by dvzrv** [comment]
excellent!
I guess we can setup letsencrypt for that subdomain now.

Thanks @danielhjames
