### ISSUE TITLE
Pay insurance for equipment

### ISSUE THREAD

**Issue by dvzrv** [linuxaudio/conference2018#3]
The VOC requires an insurance for their equipment.

**Comment by Excds** [comment]
How much is the insurance?

**Comment by dvzrv** [comment]
It was roughly 190EUR. Might be a little less, if we're using c-base equipment in parts (question to VOC pending).

**Comment by ri0t** [comment]
I think, we might be able to lend some more useful equipment (i.e. at least two more of those Canon HD cams and other less techy stuff), probably for free.

**Comment by dvzrv** [comment]
equipment list is requested

**Comment by dvzrv** [comment]
Equipment list received. Will contact insurance asap and arrange payment through cash@

**Comment by dvzrv** [comment]
Appointment on Monday will settle the contract.

**Comment by dvzrv** [comment]
this is getting more complicated as expected (because CCC should actually have an insurance for this). will get the contract in time hopefully, not sure what this will cover yet and how much

**Comment by dvzrv** [comment]
Finally done... FML.
