### ISSUE TITLE
Create mail-account for the CIS

### ISSUE THREAD

**Issue by ri0t** [linuxaudio/conference2018#30]
We need an account to send mail from linuxaudio.org.
I'd propose "bot@linuxaudio.org" if that one isn't already reserved. 

We'll primarly need this for the account registration confirmation and (future) password resetting.

@dvzrv : can you create that one and send me credentials via secure channel?

**Comment by dvzrv** [comment]
will try to do that later tonight!
-- 
https://sleepmap.de

**Comment by ri0t** [comment]
Sweet. Then we can test the heck out of this tomorrow and invite everyone as soon as the live-dns entry is done.
I'm beautifying things until then.

I've pretty much built a better openconf in the meantime, btw :D

**Comment by dvzrv** [comment]
created
