### ISSUE TITLE
Schedule extra cleaning

### ISSUE THREAD

**Issue by dvzrv** [linuxaudio/conference2018#35]
We have to schedule an extra cleaning with cultorga, sometime in the middle of the event.
This usually costs around 100EUR and eventually might be taken care of by c-base itself, if we request this.

**Comment by dvzrv** [comment]
just sent a mail to cultorga, requesting this.

**Comment by ri0t** [comment]
Depending on the cleaning time, the chairs need to be set up either in the evening or in the morning.

**Comment by dvzrv** [comment]
cultorga informed us, that it's already working on a cleaning schedule. I've synced our schedule with nielc (cultorga), so he should be sufficiently aware of our situation.

**Comment by dvzrv** [comment]
this is done in a 2 day rhythmn atm.
