### ISSUE TITLE
Announce LAC within c-base at next circle

### ISSUE THREAD

**Issue by dvzrv** [linuxaudio/conference2018#37]
We need an infotopic about LAC at the next circle (**20180601**), highlighting the following:

- [x] live video broadcasting June 7th - June 10th
- [x] a lot of workshop and paper sessions!
- [x] informal opening (with live music) on Thursday (**20180607**)
- [x] 8-channel (tape music) concert evening on Friday (**20180608**)
- [x] we need bar bots!

**Comment by ri0t** [comment]
Sent a mail to bar-crew with a bar-crew schedule

**Comment by dvzrv** [comment]
Thanks!

**Comment by dvzrv** [comment]
What's the bar bot status?
