### ISSUE TITLE
Request dedicated upstream for VOC (if needed)

### ISSUE THREAD

**Issue by dvzrv** [linuxaudio/conference2018#38]
We need to write to admax@ to consider a dedicated upstream for the VOC streaming.

**Comment by MaZderMind** [comment]
The VOC calculates 5 MBit/s per Room peak, usually more in the Range of 3 MBIt/s.

**Comment by dvzrv** [comment]
Sent a mail (with CC to conference mail) to admax@.

**Comment by dvzrv** [comment]
Now requested updated MAC adresses for VOC equipment to be priotized.

**Comment by dvzrv** [comment]
@derpeter when can we get an update on the MAC adresses? We have to inform our admins about them for higher prio, than the rest of the internal stuff at c-base.

**Comment by derpeter** [comment]
I sendet a mail with a sugestion for a setup, we woudl need to get that confirmed than i can tell you which device will be seen bei your GW.

If possible we would like to ask for an real layer2 or an vlan between the rooms. And one port in a different layer2 / vlan that leads to the gateway. The perfect setup for us would be to plug our gateway right at the patchpanel with its LAN side to the patches to the rooms and with its WAN side facing you GW. As i dont know the infra at c-base i cant tell how realistic this is.

So let me know what is possible. We could also talk about this tomorrow after the space tour, open the flight case an get the mac of the device.

**Comment by dvzrv** [comment]
Thanks! Let's discuss this Saturday evening then.

**Comment by dvzrv** [comment]
I guess, if MM won't help out and as uk is not in Berlin, the easiest would be to setup cables ourselves, as I don't trust the internal infrastructure and we don't have time for debugging this.

**Comment by dvzrv** [comment]
done that. ipb 10/10 is as good as it gets for us and I hope it's enough (as we're not getting all of it).
If the streams get to sloppy, we'll switch to LTE.
