### ISSUE TITLE
Buy coffee

### ISSUE THREAD

**Issue by dvzrv** [linuxaudio/conference2018#39]
Zappatistic coffee for the conference. We might be able to buy this through cultorga.
Needs request

**Comment by Excds** [comment]
@dvzrv Is it this type you mean? https://www.aroma-zapatista.de/

**Comment by dvzrv** [comment]
@Excds yep. but in general, if you can find something that is really good (trusting in your nation's coffee heritage ;-) ), go for it!

**Comment by Excds** [comment]
@dvzrv I guess we can order from there and have it before it's time. But, eh, how much should we get?

I like good coffee, but I'm really not the one who knows a lot about it (I may not know art, but I know what I like...).

**Comment by Excds** [comment]
![20180602_144339](https://user-images.githubusercontent.com/189418/40886864-c45cb106-673f-11e8-8aff-464a6d45cb90.jpg)
