### ISSUE TITLE
Find a time for the group photo

### ISSUE THREAD

**Issue by ri0t** [linuxaudio/conference2018#44]
* [ ] Saturday or Sunday? 
* [ ] What time?
* [ ] Add calendar item

**Comment by dvzrv** [comment]
Ideally we would do this Sunday, because half of the crew will be at native space on Saturday. Unless, we do it there, before the concert!

**Comment by ri0t** [comment]
Naaah. I do <3 native - but nah. We should do it at c-base out of historical reasons.

**Comment by dvzrv** [comment]
Getting the involved people and the highest amount of people possible in the picture completely outweighs "historical reasons". I'm thinking practical here, as that's when most of us will be in one spot.
Saturday during the day it is too much of a hassle to drive around between rehearsals. Another possible solution would be Sunday, but that's usually when some people are leaving already.

**Comment by Excds** [comment]
I guess Saturday makes more sense in the case of getting more people.
