### ISSUE TITLE
Print direction signs

### ISSUE THREAD

**Issue by dvzrv** [linuxaudio/conference2018#47]
We need a bunch of direction signs for the participants, so they'll more easily find places in c-base, but also direction signs for Rungestrasse and the backyard, so people will find the entrance without hassle.

- [x] getting to c-base
- [ ] where is mainhall
- [ ] where is ceminar
- [ ] where is soundlab
- [ ] getting to spektrum
- [ ] getting to native space

**Comment by Excds** [comment]
Depending on the weather, writing LAC in chalk on the ground together with an arrow?

**Comment by dvzrv** [comment]
Whatever floats your boat ;-)
Generally it's a lot of cobblestones there, so printouts might be easier

**Comment by ri0t** [comment]
I _could maybe_ add a map with directions on live.linuxaudio.org - not sure if i can get it to be a smooth user experience in that short time, though. Handling the map is still kind of non-trivial, sadly. 

I'm gonna give it a try and see how far this works. It is probably not a 100% replacement, though.

**Comment by dvzrv** [comment]
@ri0t please don't. There are plenty of other loose ends right now. No need to add yet another

**Comment by dvzrv** [comment]
Made this a little more clear

**Comment by Excds** [comment]
I've printed 10x of this: https://docs.google.com/presentation/d/19Z0yglI-hx2d3kDR_VvW0E8uWU-bzUlIgs-TAuEsuYs/edit?usp=sharing

**Comment by Excds** [comment]
I've also bought masking tape for putting up the printed arrows. Oh, and chalk for writing on the street.

**Comment by ri0t** [comment]
The online map is quite usable and has some detail infos about some waypoints.
The printed map is done (copy of the online map), i'll bring half a dozen copies for distribution tomorrow.
Another happy accident: We got a lot of extra large arrows (laminated!) - they're stored at the videotresen.
