### ISSUE TITLE
Prepare Native Space for concerts on Saturday

### ISSUE THREAD

**Issue by dvzrv** [linuxaudio/conference2018#49]
As artistania just blew all up in our faces, we'll move concerts on Saturday to Native Space (at Native Instruments).

This requires a few things:

- [x] order drinks through in-house caterer or use c-base stock
- [x] get information on power grid
- [ ] setup space
- [x] have 1-2 people ready to open/close the main gate for visitors at all times
- [x] find 1-2 more people from Native Instruments to help out
- [ ] setup streaming (transfer camera and additional equipment from and to c-base)

This pretty much binds me to Native Space most of the Saturday, if there's no additional person from Native Instruments helping out there, but is the best (and free!) short-term solution to this fuckup.

I'll try to cross most things off the list tomorrow.

**Comment by dvzrv** [comment]
* requested dedicated upstream for VOC (apparently we can even get RJ45, but I need IT for that)
* asked a bunch of colleagues (two already said yes)
* asked about power connection (we should have sufficient power connections for our setup)

**Comment by dvzrv** [comment]
The max upstream seems to be 790mbit, so VOC should be fine.

**Comment by dvzrv** [comment]
We have to choose between:
* ordering drinks through https://www.hoffmannbringts.de/ with in-house caterer and deal with how to pay for that (most likely we can only pay for that in cash, as the person in charge doesn't know yet, whether external payments through bank are fine)
* use c-base stock and drive it over to native space

**Comment by dvzrv** [comment]
@anwaldt @riot @excds please respond regarding the drinks asap. Needs to be clarified by tomorrow

**Comment by Excds** [comment]
@dvzrv I can put up the cash if I get a receipt. Well, depends on how much. But it should be fine.

**Comment by Excds** [comment]
Waiting for the invoice so I can pay and get the order going...

**Comment by dvzrv** [comment]
@Excds I'm not sure that's actually the preferred way. We have to somehow use the provided sponsoring towards LAC. It would probably be possible to just use c-base stock, but I have no clue as to how that is handled.
I also wouldn't know what to choose from in the catalogue of a gazillion drinks.

**Comment by dvzrv** [comment]
one camera and additional equipment needs to be transferred to native space from c-base and back afterwards (for streaming).

**Comment by dvzrv** [comment]
Two sets of keys to gate and room acquired yesterday
