### ISSUE TITLE
Prepare soundlab

### ISSUE THREAD

**Issue by dvzrv** [linuxaudio/conference2018#51]
Soundlab needs to be prepared for
* spontaneous meetings
* showcases

**Comment by Excds** [comment]
@dvzrv For this we'd basically just need to tidy a bit and to prepare some connections to sound?

What's the status of the projector btw?

**Comment by ri0t** [comment]
@Excds  -I have mounted the mount but it is pretty much unusable as is - the distance to the screen is (as i warned about) too far and keystone can't really be corrected right now. Also, there's a signal cable missing, but c_ascha has some, we might be able to use.

**Comment by dvzrv** [comment]
We should think of an additional audio interface to use with the HEDD speakers, unless we can also hook them up to the current system.
