### ISSUE TITLE
Get beverages to/for NativeSpace

### ISSUE THREAD

**Issue by ri0t** [linuxaudio/conference2018#53]
We'll need a lot of drinks at the concert venue on Saturday.
Either order some there specifically or transport stuff from c-base over.

We'll possibly also need a few barbots there. Right, @dvzrv?

**Comment by dvzrv** [comment]
As there is no real "bar situation", but more of a countertop of a kitchen, this is not so easy, but could be arranged somehow. Also, fridge should only be opened before, during break and after the concerts, as it's seated and most likely streamed.

**Comment by dvzrv** [comment]
This also entails getting empty bottles etc. back to c-base/ picked up.

**Comment by dvzrv** [comment]
As we can now use c-base stock, we need change in coins. Plenty!

**Comment by ri0t** [comment]
I'll prepare a bartender purse, latest wednesday evening (after the board meets).

**Comment by dvzrv** [comment]
We only need to arrange a time schedule for the pickup. We have a transporter available that day for the studio equipment anyways.

**Comment by dvzrv** [comment]
@ri0t can you make a list of what we will bring?

**Comment by ri0t** [comment]
Yeah, tomorrow. How much space do we have for crates? A Robbe? Enough? Hmm.
