### ISSUE TITLE
Buy vegetarian and non-vegetarian food for barbecue

### ISSUE THREAD

**Issue by dvzrv** [linuxaudio/conference2018#54]
Food has to be bought for Thursday's barbecue. This will be for 60+ people.
This should entail vegetarian and non-vegetarian solutions. We will also need dishes most likely, as there will be many people.
Money will be reimbursed from c-base, so keep the receipt.

**Comment by ri0t** [comment]
How much budget can/should we use?

**Comment by dvzrv** [comment]
I'll know after paying the insurance tomorrow afternoon.

**Comment by ri0t** [comment]
Thanks to @excds and c_ascha, that has been done.
