### ISSUE TITLE
Clear seminarroom

### ISSUE THREAD

**Issue by ri0t** [linuxaudio/conference2018#55]
There is lots of unnecessary and disturbing fluff in there, right now. c_ascha offered help, as he is the last ceminar-orga person.

**Comment by Excds** [comment]
Fixed yesterday.

The floor could use another sweep and just wiping the tables before any workshops.

**Comment by dvzrv** [comment]
What is the status on the projector in there? We need to send out another reminder as to what to bring, if you want to present there.
Are we sure, we have HDMI and VGA connection available? Can we adapt to anything?

What about sound? Can we use the HEDD speakers with an audio interface of sorts in there?

**Comment by ri0t** [comment]
Projector there is fine - but only a VGA cable.

**Comment by dvzrv** [comment]
iirc we used my HDMI cable last time... I hope I can find it!
