### ISSUE TITLE
Infodesk (bar)

### ISSUE THREAD

**Issue by dvzrv** [linuxaudio/conference2018#56]
Mainhall bar needs the following things:

- [x] printed proceedings (separate stock for visitors, that pre-ordered them!)
- [ ] spare cash to deal with selling of printed proceedings
- [x] donation box
- [ ] license, streaming, copyright, privacy agreement for presenters
- [x] name tags for registered visitors

**Comment by Excds** [comment]
@dvzrv For the name tags, should we just have some stickers and permanent markers so people can write themselves?

**Comment by dvzrv** [comment]
@anwaldt please review the privacy statement and the e-mail sent out to the presenters to formulate the agreement for the presenters.
Ideally this agreement is signed a couple of hours before the presentation, so it gives enough leeway to setup the streams as intended. Therefore it needs to be at the info desc on Thursday already.
