### ISSUE TITLE
Collection of potential sponsors

### ISSUE THREAD

**Issue by ri0t** [linuxaudio/conference2018#7]
- [ ] EVE Audio (@ri0t)
- [ ] Schneiders Laden / Büro or Superbooth (@ri0t)
- [ ] Bitwig (@ri0t)
- [ ] Roland (@ri0t)
- [ ] u-He (@ri0t)
- [x] Ableton (@Excds )
- [ ] Adam (@dvzrv)
- [x] MOD (@dvzrv)
- [ ] Native (@anwaldt )
- [ ] RME (@anwaldt )
- [ ] Just Music (@anwaldt )
- [x] HEDD (@anwaldt )
- [ ] Behringér (@anwaldt )

**Comment by harryhaaren** [comment]
Suggestion to talk to MOD Devices too.

**Comment by Excds** [comment]
I had a lunch with a friend who works at Ableton yesterday, and she's exactly the person to talk about this. She says that they would be interested and that they have a budget for sponsorships. So, how do we go about this? They would probably want to have their logo somewhere, but we don't want to have company logos put up at c-base. So, what about adding logos of the sponsors to what is screencast and put in the videos? Like prefixing everything with LAC2018 and the sponsors? That would probably add more value to the sponsors in the long run since it would show them when people would be watching the videos afterwards.

Thoughts?

I'd also like some input on what we'd like out of the sponsorship.

**Comment by Excds** [comment]
@dvzrv @ri0t 
Update: I just had a meeting with people from Ableton. Yes, they are willing to sponsor us and they would be fine with having their logo on a sponsor's slide when starting presentations. We'll get the proper logo package from them.

Questions:
1: Do we have an organization that is officially organizing the conference? If we're going to get sponsorship from Ableton, then they would do that based on transferring money to a bank account and it would be best if that's for an organization.
2: How much money do we want? I've said that we would like minimum €500, but I don't think it's impossible to ask for maybe more. We should maybe then just have a better statement than "More money please"?
3: Do we mind if Ableton promotes the conference (i.e. mentions the conference in tweets and such)? (I said that we would welcome it.)

So, for questions 1 and 2 I'd need some input and then I can send an email to Céline and CC the organizer mailing list for further discussions?

**Comment by Excds** [comment]
Ok, so I got this email now:

> Hey Daniel,
> 
> Thanks again for coming over this morning.
> 
> For whom it may concern, please find our logo file for the sponsorship attached.
> 
> The sooner we can get some kind of invoice for our 500€ sponsorship, the sooner we can pay it. 
> (Our Accounting team is a bit swamped so I am expecting payment delays we should consider.)
> 
> Here would be the billing information:
> 
> Ableton AG
> Celine Dedaj
> Schönhauser Allee 6-7
> D-10119 Berlin
> Deutschland
> VAT ID: DE204128565
> 
> Let me know if you need anything else!
> 
> Cheers
> Céline

**Comment by dvzrv** [comment]
@Excds that sounds wonderful!

> 1: Do we have an organization that is officially organizing the conference?

That would probably be the TU (and maybe @anwaldt can say more about that). However, I think they have the issue of having separate in and outgoing accounts, which makes dealing with sponsorship a pain.
I think a better way would be to use c-base for it, as it can receive donations (I'll ask count right now).

> 2: How much money do we want?

This we need to cross check with the possible venues to rent.
@anwaldt It was around 500 for one of the places in NK, if I remember correctly, right?

> 3: Do we mind if Ableton promotes the conference

I don't.

**Comment by Excds** [comment]
@dvzrv So then we can get a c-base branded invoice to send?

**Comment by dvzrv** [comment]
Most likely. Waiting for cultorga now. Cash said, it'll work.

**Comment by Excds** [comment]
"Cash said, it'll work"??

**Comment by dvzrv** [comment]
cashmaster, aka count

**Comment by Excds** [comment]
@dvzrv Any response on creating an invoice?

**Comment by dvzrv** [comment]
Sorry, been too busy.
They can send their request for the invoice directly to cultorga@c-base.org


-- 
https://sleepmap.de

**Comment by Excds** [comment]
@dvzrv We should be the ones sending an invoice to Ableton. But, ehm, so I just send an email to cultorga asking for an invoice with specific details that I can send to Ableton?

I don't know the usual procedure and information needed for invoices here in Germany...

**Comment by dvzrv** [comment]
Ah well, I can ask him to do that, too.
Wasn't sure, if Ableton has everything they need and it might just be easier for them to deal with nielc (cultorga) directly instead of us middlemanning for them.

**Comment by dvzrv** [comment]
@Excds seems that nielc will write an invoice and send it to Ableton (probably today).
Sorry for the delay.

**Comment by dvzrv** [comment]
I have included Ableton on the website. Processing MOD now.

**Comment by dvzrv** [comment]
Still need to include HEDD for hardware sponsorship, but I'll close this now, as I don't think there's more coming in. If so, reopen
