### ISSUE TITLE
plan excursions and (tech) tours

### ISSUE THREAD

**Issue by anwaldt** [linuxaudio/conference2018#9]
- [ ] TU Berlin (studio tour) [@anwaldt]
- [ ] AdK (tour through the studio - (@anwaldt)
- [ ] Eve Audio's fabrication & accoustic chambers (perhaps, gotta ask first) (@ri0t )
- [ ] Schneiders Laden (well, that is a freebie, but we could perhaps extend it somehow) (@ri0t )

**Comment by dvzrv** [comment]
Unlikely, that this is going to happen after the tracks on Sunday.
If someone is willing to host/ organize these, reopen.
